//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;

namespace Algolia.Search.Abtesting.Models
{
  /// <summary>
  /// AbTestsVariantSearchParams
  /// </summary>
  [DataContract(Name = "abTestsVariantSearchParams")]
  public partial class AbTestsVariantSearchParams : IEquatable<AbTestsVariantSearchParams>
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="AbTestsVariantSearchParams" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected AbTestsVariantSearchParams() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="AbTestsVariantSearchParams" /> class.
    /// </summary>
    /// <param name="index">A/B test index. (required).</param>
    /// <param name="trafficPercentage">A/B test traffic percentage. (required).</param>
    /// <param name="description">A/B test description..</param>
    /// <param name="customSearchParameters">customSearchParameters (required).</param>
    public AbTestsVariantSearchParams(string index = default(string), int trafficPercentage = default(int), string description = default(string), Object customSearchParameters = default(Object))
    {
      // to ensure "index" is required (not null)
      if (index == null)
      {
        throw new ArgumentNullException("index is a required property for AbTestsVariantSearchParams and cannot be null");
      }
      this.Index = index;
      this.TrafficPercentage = trafficPercentage;
      // to ensure "customSearchParameters" is required (not null)
      if (customSearchParameters == null)
      {
        throw new ArgumentNullException("customSearchParameters is a required property for AbTestsVariantSearchParams and cannot be null");
      }
      this.CustomSearchParameters = customSearchParameters;
      this.Description = description;
    }

    /// <summary>
    /// A/B test index.
    /// </summary>
    /// <value>A/B test index.</value>
    [DataMember(Name = "index", IsRequired = true, EmitDefaultValue = true)]
    public string Index { get; set; }

    /// <summary>
    /// A/B test traffic percentage.
    /// </summary>
    /// <value>A/B test traffic percentage.</value>
    [DataMember(Name = "trafficPercentage", IsRequired = true, EmitDefaultValue = true)]
    public int TrafficPercentage { get; set; }

    /// <summary>
    /// A/B test description.
    /// </summary>
    /// <value>A/B test description.</value>
    [DataMember(Name = "description", EmitDefaultValue = false)]
    public string Description { get; set; }

    /// <summary>
    /// Gets or Sets CustomSearchParameters
    /// </summary>
    [DataMember(Name = "customSearchParameters", IsRequired = true, EmitDefaultValue = true)]
    public Object CustomSearchParameters { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      StringBuilder sb = new StringBuilder();
      sb.Append("class AbTestsVariantSearchParams {\n");
      sb.Append("  Index: ").Append(Index).Append("\n");
      sb.Append("  TrafficPercentage: ").Append(TrafficPercentage).Append("\n");
      sb.Append("  Description: ").Append(Description).Append("\n");
      sb.Append("  CustomSearchParameters: ").Append(CustomSearchParameters).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
      return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
      return this.Equals(input as AbTestsVariantSearchParams);
    }

    /// <summary>
    /// Returns true if AbTestsVariantSearchParams instances are equal
    /// </summary>
    /// <param name="input">Instance of AbTestsVariantSearchParams to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(AbTestsVariantSearchParams input)
    {
      if (input == null)
      {
        return false;
      }
      return
          (
              this.Index == input.Index ||
              (this.Index != null &&
              this.Index.Equals(input.Index))
          ) &&
          (
              this.TrafficPercentage == input.TrafficPercentage ||
              this.TrafficPercentage.Equals(input.TrafficPercentage)
          ) &&
          (
              this.Description == input.Description ||
              (this.Description != null &&
              this.Description.Equals(input.Description))
          ) &&
          (
              this.CustomSearchParameters == input.CustomSearchParameters ||
              (this.CustomSearchParameters != null &&
              this.CustomSearchParameters.Equals(input.CustomSearchParameters))
          );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      unchecked // Overflow is fine, just wrap
      {
        int hashCode = 41;
        if (this.Index != null)
        {
          hashCode = (hashCode * 59) + this.Index.GetHashCode();
        }
        hashCode = (hashCode * 59) + this.TrafficPercentage.GetHashCode();
        if (this.Description != null)
        {
          hashCode = (hashCode * 59) + this.Description.GetHashCode();
        }
        if (this.CustomSearchParameters != null)
        {
          hashCode = (hashCode * 59) + this.CustomSearchParameters.GetHashCode();
        }
        return hashCode;
      }
    }

  }

}
