//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Analytics;

/// <summary>
/// GetTopFiltersNoResultsValues
/// </summary>
[DataContract(Name = "getTopFiltersNoResultsValues")]
public partial class GetTopFiltersNoResultsValues
{
  /// <summary>
  /// Initializes a new instance of the GetTopFiltersNoResultsValues class.
  /// </summary>
  [JsonConstructor]
  public GetTopFiltersNoResultsValues() { }
  /// <summary>
  /// Initializes a new instance of the GetTopFiltersNoResultsValues class.
  /// </summary>
  /// <param name="count">Number of occurrences. (required).</param>
  /// <param name="values">Filters with no results. (required).</param>
  public GetTopFiltersNoResultsValues(int count, List<GetTopFiltersNoResultsValue> values)
  {
    Count = count;
    Values = values ?? throw new ArgumentNullException(nameof(values));
  }

  /// <summary>
  /// Number of occurrences.
  /// </summary>
  /// <value>Number of occurrences.</value>
  [DataMember(Name = "count")]
  public int Count { get; set; }

  /// <summary>
  /// Filters with no results.
  /// </summary>
  /// <value>Filters with no results.</value>
  [DataMember(Name = "values")]
  public List<GetTopFiltersNoResultsValue> Values { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class GetTopFiltersNoResultsValues {\n");
    sb.Append("  Count: ").Append(Count).Append("\n");
    sb.Append("  Values: ").Append(Values).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonConvert.SerializeObject(this, Formatting.Indented);
  }

}

