//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Analytics;

/// <summary>
/// TopHit
/// </summary>
[DataContract(Name = "topHit")]
[JsonObject(MemberSerialization.OptOut)]
public partial class TopHit
{
  /// <summary>
  /// Initializes a new instance of the TopHit class.
  /// </summary>
  [JsonConstructor]
  public TopHit() { }
  /// <summary>
  /// Initializes a new instance of the TopHit class.
  /// </summary>
  /// <param name="hit">Hit. (required).</param>
  /// <param name="count">Number of occurrences. (required).</param>
  public TopHit(string hit, int? count)
  {
    Hit = hit ?? throw new ArgumentNullException(nameof(hit));
    Count = count;
  }

  /// <summary>
  /// Hit.
  /// </summary>
  /// <value>Hit.</value>
  [DataMember(Name = "hit", IsRequired = true, EmitDefaultValue = false)]
  public string Hit { get; set; }

  /// <summary>
  /// Number of occurrences.
  /// </summary>
  /// <value>Number of occurrences.</value>
  [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = false)]
  public int? Count { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class TopHit {\n");
    sb.Append("  Hit: ").Append(Hit).Append("\n");
    sb.Append("  Count: ").Append(Count).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonConvert.SerializeObject(this, Formatting.Indented);
  }

}

