language: objective-c
before_install:
- wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
- sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  -target /
script:
- mono --runtime=v4.0 .nuget/NuGet.exe restore
- EnableNuGetPackageRestore=true xbuild Algolia.Search/Algolia.Search.csproj
- EnableNuGetPackageRestore=true xbuild Algolia.Search.NET4.0/Algolia.Search.NET4.0.csproj
- EnableNuGetPackageRestore=true xbuild Algolia.Search.Test/Algolia.Search.Test.csproj
- mono --runtime=v4.0 packages/NUnit.Runners.2.6.3/tools/nunit-console.exe Algolia.Search.Test/bin/Debug/Algolia.Search.Test.dll
env:
  global:
  - secure: dScxAee5Ge3BEG+g5oTbhfqnpGnx7hJS5n2Dnr3M8AKUpTxO2Y+XGUBNquPPM2Uw0O2DhBIXE6apwElJBxBEWTn7FB0WtsQ8Ei1d+AXM/B10Tw+mPTp9a6jd8vORtAaJo6ku7/ePoUVnP2cIGSdoAIlN2WX8TVC4WH45df3dGmM=
  - secure: seqywn/J3Fe6LhbQAdB6SQDjXvMdBPSylqlO2ERtM2KrOBHl6zQlZtUAUHriWcATEFnAXY7LguUOWG9lzEG6tAhqRVCvL0TcF7kfcE2p4UwPCCjSKwjujNgIFmjjovFgYrNoccAbjGELq8hLYTnf22KmIRlz8+yYfhPTmi6457s=
  matrix:
  - MONO_VERSION="3.2.7"
