//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Algolia.Search.Ingestion.Client.FileParameter;
using OpenAPIDateConverter = Algolia.Search.Ingestion.Client.OpenAPIDateConverter;

namespace Algolia.Search.Ingestion.Models
{
  /// <summary>
  /// DeleteResponse
  /// </summary>
  [DataContract(Name = "DeleteResponse")]
  public partial class DeleteResponse : IEquatable<DeleteResponse>, IValidatableObject
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="DeleteResponse" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected DeleteResponse() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="DeleteResponse" /> class.
    /// </summary>
    /// <param name="deletedAt">Date of deletion (RFC3339 format). (required).</param>
    public DeleteResponse(string deletedAt = default(string))
    {
      // to ensure "deletedAt" is required (not null)
      if (deletedAt == null)
      {
        throw new ArgumentNullException("deletedAt is a required property for DeleteResponse and cannot be null");
      }
      this.DeletedAt = deletedAt;
    }

    /// <summary>
    /// Date of deletion (RFC3339 format).
    /// </summary>
    /// <value>Date of deletion (RFC3339 format).</value>
    [DataMember(Name = "deletedAt", IsRequired = true, EmitDefaultValue = true)]
    public string DeletedAt { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      StringBuilder sb = new StringBuilder();
      sb.Append("class DeleteResponse {\n");
      sb.Append("  DeletedAt: ").Append(DeletedAt).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
      return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
      return this.Equals(input as DeleteResponse);
    }

    /// <summary>
    /// Returns true if DeleteResponse instances are equal
    /// </summary>
    /// <param name="input">Instance of DeleteResponse to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(DeleteResponse input)
    {
      if (input == null)
      {
        return false;
      }
      return
          (
              this.DeletedAt == input.DeletedAt ||
              (this.DeletedAt != null &&
              this.DeletedAt.Equals(input.DeletedAt))
          );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      unchecked // Overflow is fine, just wrap
      {
        int hashCode = 41;
        if (this.DeletedAt != null)
        {
          hashCode = (hashCode * 59) + this.DeletedAt.GetHashCode();
        }
        return hashCode;
      }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }
  }

}
