//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Algolia.Search.Ingestion.Client.FileParameter;
using OpenAPIDateConverter = Algolia.Search.Ingestion.Client.OpenAPIDateConverter;

namespace Algolia.Search.Ingestion.Models
{
  /// <summary>
  /// The input for a &#x60;schedule&#x60; task whose source is of type &#x60;bigquery&#x60; and for which extracted data spans a fixed number of days.
  /// </summary>
  [DataContract(Name = "ScheduleDateUtilsInput")]
  public partial class ScheduleDateUtilsInput : IEquatable<ScheduleDateUtilsInput>, IValidatableObject
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="ScheduleDateUtilsInput" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected ScheduleDateUtilsInput() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="ScheduleDateUtilsInput" /> class.
    /// </summary>
    /// <param name="timeframe">The timeframe of the extraction, in number of days from today. (required).</param>
    public ScheduleDateUtilsInput(int timeframe = default(int))
    {
      this.Timeframe = timeframe;
    }

    /// <summary>
    /// The timeframe of the extraction, in number of days from today.
    /// </summary>
    /// <value>The timeframe of the extraction, in number of days from today.</value>
    [DataMember(Name = "timeframe", IsRequired = true, EmitDefaultValue = true)]
    public int Timeframe { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      StringBuilder sb = new StringBuilder();
      sb.Append("class ScheduleDateUtilsInput {\n");
      sb.Append("  Timeframe: ").Append(Timeframe).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
      return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
      return this.Equals(input as ScheduleDateUtilsInput);
    }

    /// <summary>
    /// Returns true if ScheduleDateUtilsInput instances are equal
    /// </summary>
    /// <param name="input">Instance of ScheduleDateUtilsInput to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ScheduleDateUtilsInput input)
    {
      if (input == null)
      {
        return false;
      }
      return
          (
              this.Timeframe == input.Timeframe ||
              this.Timeframe.Equals(input.Timeframe)
          );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      unchecked // Overflow is fine, just wrap
      {
        int hashCode = 41;
        hashCode = (hashCode * 59) + this.Timeframe.GetHashCode();
        return hashCode;
      }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      // Timeframe (int) maximum
      if (this.Timeframe > (int)30)
      {
        yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Timeframe, must be a value less than or equal to 30.", new[] { "Timeframe" });
      }

      // Timeframe (int) minimum
      if (this.Timeframe < (int)1)
      {
        yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Timeframe, must be a value greater than or equal to 1.", new[] { "Timeframe" });
      }

      yield break;
    }
  }

}
