//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.Reflection;
using Algolia.Search.Models;

namespace Algolia.Search.Models.Ingestion
{
  /// <summary>
  /// TaskCreateTrigger
  /// </summary>
  [JsonConverter(typeof(TaskCreateTriggerJsonConverter))]
  [DataContract(Name = "TaskCreateTrigger")]
  public partial class TaskCreateTrigger : AbstractSchema
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="TaskCreateTrigger" /> class
    /// with the <see cref="OnDemandTriggerInput" /> class
    /// </summary>
    /// <param name="actualInstance">An instance of OnDemandTriggerInput.</param>
    public TaskCreateTrigger(OnDemandTriggerInput actualInstance)
    {
      IsNullable = false;
      SchemaType = "oneOf";
      ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="TaskCreateTrigger" /> class
    /// with the <see cref="ScheduleTriggerInput" /> class
    /// </summary>
    /// <param name="actualInstance">An instance of ScheduleTriggerInput.</param>
    public TaskCreateTrigger(ScheduleTriggerInput actualInstance)
    {
      IsNullable = false;
      SchemaType = "oneOf";
      ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="TaskCreateTrigger" /> class
    /// with the <see cref="SubscriptionTrigger" /> class
    /// </summary>
    /// <param name="actualInstance">An instance of SubscriptionTrigger.</param>
    public TaskCreateTrigger(SubscriptionTrigger actualInstance)
    {
      IsNullable = false;
      SchemaType = "oneOf";
      ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
    }


    private Object _actualInstance;

    /// <summary>
    /// Gets or Sets ActualInstance
    /// </summary>
    public override Object ActualInstance
    {
      get
      {
        return _actualInstance;
      }
      set
      {
        this._actualInstance = value;
      }
    }

    /// <summary>
    /// Get the actual instance of `OnDemandTriggerInput`. If the actual instance is not `OnDemandTriggerInput`,
    /// the InvalidClassException will be thrown
    /// </summary>
    /// <returns>An instance of OnDemandTriggerInput</returns>
    public OnDemandTriggerInput AsOnDemandTriggerInput()
    {
      return (OnDemandTriggerInput)ActualInstance;
    }

    /// <summary>
    /// Get the actual instance of `ScheduleTriggerInput`. If the actual instance is not `ScheduleTriggerInput`,
    /// the InvalidClassException will be thrown
    /// </summary>
    /// <returns>An instance of ScheduleTriggerInput</returns>
    public ScheduleTriggerInput AsScheduleTriggerInput()
    {
      return (ScheduleTriggerInput)ActualInstance;
    }

    /// <summary>
    /// Get the actual instance of `SubscriptionTrigger`. If the actual instance is not `SubscriptionTrigger`,
    /// the InvalidClassException will be thrown
    /// </summary>
    /// <returns>An instance of SubscriptionTrigger</returns>
    public SubscriptionTrigger AsSubscriptionTrigger()
    {
      return (SubscriptionTrigger)ActualInstance;
    }


    /// <summary>
    /// Check if the actual instance is of `OnDemandTriggerInput` type.
    /// </summary>
    /// <returns>Whether or not the instance is the type</returns>
    public bool IsOnDemandTriggerInput()
    {
      return ActualInstance.GetType() == typeof(OnDemandTriggerInput);
    }

    /// <summary>
    /// Check if the actual instance is of `ScheduleTriggerInput` type.
    /// </summary>
    /// <returns>Whether or not the instance is the type</returns>
    public bool IsScheduleTriggerInput()
    {
      return ActualInstance.GetType() == typeof(ScheduleTriggerInput);
    }

    /// <summary>
    /// Check if the actual instance is of `SubscriptionTrigger` type.
    /// </summary>
    /// <returns>Whether or not the instance is the type</returns>
    public bool IsSubscriptionTrigger()
    {
      return ActualInstance.GetType() == typeof(SubscriptionTrigger);
    }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class TaskCreateTrigger {\n");
      sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public override string ToJson()
    {
      return JsonConvert.SerializeObject(ActualInstance, SerializerSettings);
    }

    /// <summary>
    /// Converts the JSON string into an instance of TaskCreateTrigger
    /// </summary>
    /// <param name="jsonString">JSON string</param>
    /// <returns>An instance of TaskCreateTrigger</returns>
    public static TaskCreateTrigger FromJson(string jsonString)
    {
      TaskCreateTrigger newTaskCreateTrigger = null;

      if (string.IsNullOrEmpty(jsonString))
      {
        return newTaskCreateTrigger;
      }
      try
      {
        return new TaskCreateTrigger(JsonConvert.DeserializeObject<OnDemandTriggerInput>(jsonString, AdditionalPropertiesSerializerSettings));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OnDemandTriggerInput: {1}", jsonString, exception.ToString()));
      }
      try
      {
        return new TaskCreateTrigger(JsonConvert.DeserializeObject<ScheduleTriggerInput>(jsonString, AdditionalPropertiesSerializerSettings));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ScheduleTriggerInput: {1}", jsonString, exception.ToString()));
      }
      try
      {
        return new TaskCreateTrigger(JsonConvert.DeserializeObject<SubscriptionTrigger>(jsonString, AdditionalPropertiesSerializerSettings));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SubscriptionTrigger: {1}", jsonString, exception.ToString()));
      }

      throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
    }

  }

  /// <summary>
  /// Custom JSON converter for TaskCreateTrigger
  /// </summary>
  public class TaskCreateTriggerJsonConverter : JsonConverter
  {
    /// <summary>
    /// To write the JSON string
    /// </summary>
    /// <param name="writer">JSON writer</param>
    /// <param name="value">Object to be converted into a JSON string</param>
    /// <param name="serializer">JSON Serializer</param>
    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
      writer.WriteRawValue((string)(typeof(TaskCreateTrigger).GetMethod("ToJson").Invoke(value, null)));
    }

    /// <summary>
    /// To convert a JSON string into an object
    /// </summary>
    /// <param name="reader">JSON reader</param>
    /// <param name="objectType">Object type</param>
    /// <param name="existingValue">Existing value</param>
    /// <param name="serializer">JSON Serializer</param>
    /// <returns>The object converted from the JSON string</returns>
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
      if (reader.TokenType != JsonToken.Null)
      {
        return objectType.GetMethod("FromJson").Invoke(null, new[] { JObject.Load(reader).ToString(Formatting.None) });
      }
      return null;
    }

    /// <summary>
    /// Check if the object can be converted
    /// </summary>
    /// <param name="objectType">Object type</param>
    /// <returns>True if the object can be converted</returns>
    public override bool CanConvert(Type objectType)
    {
      return false;
    }
  }

}
