//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Ingestion;

/// <summary>
/// Authentication input for Basic login with username and password.
/// </summary>
[DataContract(Name = "AuthBasic")]
[JsonObject(MemberSerialization.OptOut)]
public partial class AuthBasic
{
  /// <summary>
  /// Initializes a new instance of the AuthBasic class.
  /// </summary>
  [JsonConstructor]
  public AuthBasic() { }
  /// <summary>
  /// Initializes a new instance of the AuthBasic class.
  /// </summary>
  /// <param name="username">username (required).</param>
  /// <param name="password">password (required).</param>
  public AuthBasic(string username, string password)
  {
    Username = username ?? throw new ArgumentNullException(nameof(username));
    Password = password ?? throw new ArgumentNullException(nameof(password));
  }

  /// <summary>
  /// Gets or Sets Username
  /// </summary>
  [DataMember(Name = "username")]
  public string Username { get; set; }

  /// <summary>
  /// Gets or Sets Password
  /// </summary>
  [DataMember(Name = "password")]
  public string Password { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class AuthBasic {\n");
    sb.Append("  Username: ").Append(Username).Append("\n");
    sb.Append("  Password: ").Append(Password).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonConvert.SerializeObject(this, Formatting.Indented);
  }

}

