//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Text;
using System.Linq;
using System.Text.Json.Serialization;
using System.Collections.Generic;
using Algolia.Search.Serializer;
using System.Text.Json;

namespace Algolia.Search.Models.Ingestion;

/// <summary>
/// DestinationIndexPrefix
/// </summary>
public partial class DestinationIndexPrefix
{
  /// <summary>
  /// Initializes a new instance of the DestinationIndexPrefix class.
  /// </summary>
  [JsonConstructor]
  public DestinationIndexPrefix() { }
  /// <summary>
  /// Initializes a new instance of the DestinationIndexPrefix class.
  /// </summary>
  /// <param name="indexPrefix">String added to the beginning of all indices created by this destination. (required).</param>
  public DestinationIndexPrefix(string indexPrefix)
  {
    IndexPrefix = indexPrefix ?? throw new ArgumentNullException(nameof(indexPrefix));
  }

  /// <summary>
  /// String added to the beginning of all indices created by this destination.
  /// </summary>
  /// <value>String added to the beginning of all indices created by this destination.</value>
  [JsonPropertyName("indexPrefix")]
  public string IndexPrefix { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class DestinationIndexPrefix {\n");
    sb.Append("  IndexPrefix: ").Append(IndexPrefix).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not DestinationIndexPrefix input)
    {
      return false;
    }

    return
        (IndexPrefix == input.IndexPrefix || (IndexPrefix != null && IndexPrefix.Equals(input.IndexPrefix)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (IndexPrefix != null)
      {
        hashCode = (hashCode * 59) + IndexPrefix.GetHashCode();
      }
      return hashCode;
    }
  }

}

