//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Text;
using System.Linq;
using System.Text.Json.Serialization;
using System.Collections.Generic;
using Algolia.Search.Serializer;
using System.Text.Json;

namespace Algolia.Search.Models.Ingestion;

/// <summary>
/// EmailNotifications
/// </summary>
public partial class EmailNotifications
{
  /// <summary>
  /// Initializes a new instance of the EmailNotifications class.
  /// </summary>
  public EmailNotifications()
  {
  }

  /// <summary>
  /// Whether to send email notifications, note that this doesn't prevent the task from being blocked.
  /// </summary>
  /// <value>Whether to send email notifications, note that this doesn't prevent the task from being blocked.</value>
  [JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class EmailNotifications {\n");
    sb.Append("  Enabled: ").Append(Enabled).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not EmailNotifications input)
    {
      return false;
    }

    return
        (Enabled == input.Enabled || Enabled.Equals(input.Enabled));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      hashCode = (hashCode * 59) + Enabled.GetHashCode();
      return hashCode;
    }
  }

}

