//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Ingestion;

/// <summary>
/// Property by which to sort the list of task run events.
/// </summary>
/// <value>Property by which to sort the list of task run events.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<EventSortKeys>))]
public enum EventSortKeys
{
  /// <summary>
  /// Enum Status for value: status
  /// </summary>
  [JsonPropertyName("status")]
  Status = 1,

  /// <summary>
  /// Enum Type for value: type
  /// </summary>
  [JsonPropertyName("type")]
  Type = 2,

  /// <summary>
  /// Enum PublishedAt for value: publishedAt
  /// </summary>
  [JsonPropertyName("publishedAt")]
  PublishedAt = 3,
}
