//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Ingestion;

/// <summary>
/// API response for creating a transformation.
/// </summary>
public partial class TransformationCreateResponse
{
  /// <summary>
  /// Initializes a new instance of the TransformationCreateResponse class.
  /// </summary>
  [JsonConstructor]
  public TransformationCreateResponse() { }

  /// <summary>
  /// Initializes a new instance of the TransformationCreateResponse class.
  /// </summary>
  /// <param name="transformationID">Universally unique identifier (UUID) of a transformation. (required).</param>
  /// <param name="createdAt">Date and time when the resource was created, in RFC 3339 format. (required).</param>
  public TransformationCreateResponse(string transformationID, string createdAt)
  {
    TransformationID =
      transformationID ?? throw new ArgumentNullException(nameof(transformationID));
    CreatedAt = createdAt ?? throw new ArgumentNullException(nameof(createdAt));
  }

  /// <summary>
  /// Universally unique identifier (UUID) of a transformation.
  /// </summary>
  /// <value>Universally unique identifier (UUID) of a transformation.</value>
  [JsonPropertyName("transformationID")]
  public string TransformationID { get; set; }

  /// <summary>
  /// Date and time when the resource was created, in RFC 3339 format.
  /// </summary>
  /// <value>Date and time when the resource was created, in RFC 3339 format.</value>
  [JsonPropertyName("createdAt")]
  public string CreatedAt { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class TransformationCreateResponse {\n");
    sb.Append("  TransformationID: ").Append(TransformationID).Append("\n");
    sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not TransformationCreateResponse input)
    {
      return false;
    }

    return (
        TransformationID == input.TransformationID
        || (TransformationID != null && TransformationID.Equals(input.TransformationID))
      )
      && (CreatedAt == input.CreatedAt || (CreatedAt != null && CreatedAt.Equals(input.CreatedAt)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (TransformationID != null)
      {
        hashCode = (hashCode * 59) + TransformationID.GetHashCode();
      }
      if (CreatedAt != null)
      {
        hashCode = (hashCode * 59) + CreatedAt.GetHashCode();
      }
      return hashCode;
    }
  }
}
