/*
* Algolia Monitoring API
*
* The Monitoring API lets you check the status and performance of your Algolia infrastructure.  > **Note**: The Monitoring API is available on [Premium plans](https://www.algolia.com/pricing/) and plans including the Enterprise add-on. 
*
* The version of the OpenAPI document: 1.0.0
* Generated by: https://github.com/openapitools/openapi-generator.git
*/


using System;
using System.Collections.Generic;
using Algolia.Search.Models.Common;
using Algolia.Search.Transport;
using Algolia.Search.Utils;

namespace Algolia.Search.Clients;

/// <summary>
/// Monitoring client configuration
/// </summary>
public sealed class MonitoringConfig : AlgoliaConfig
{
  /// <summary>
  /// The configuration of the Monitoring client
  /// A client should have it's own configuration ie on configuration per client instance
  /// </summary>
  /// <param name="appId">Your application ID</param>
  /// <param name="apiKey">Your API Key</param>
  public MonitoringConfig(string appId, string apiKey) : base(appId, apiKey, "Monitoring")
  {
    DefaultHosts = GetDefaultHosts();
    Compression = CompressionType.None;
  }
  private static List<StatefulHost> GetDefaultHosts()
  {
    return new List<StatefulHost>
  {
    new()
    {
      Url = "status.algolia.com",
      Up = true,
      LastUse = DateTime.UtcNow,
      Accept =  CallType.Read | CallType.Write
    }
  };
  }
}

