//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Composition;

/// <summary>
/// Ordering to apply on the items retrieved from the external provider. 'default' uses the relevance ranking from the Algolia retrieval step. 'providerDefined' uses the ordering returned by the external provider.
/// </summary>
/// <value>Ordering to apply on the items retrieved from the external provider. 'default' uses the relevance ranking from the Algolia retrieval step. 'providerDefined' uses the ordering returned by the external provider. </value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<ExternalProviderOrdering>))]
public enum ExternalProviderOrdering
{
  /// <summary>
  /// Enum Default for value: default
  /// </summary>
  [JsonPropertyName("default")]
  Default = 1,

  /// <summary>
  /// Enum ProviderDefined for value: providerDefined
  /// </summary>
  [JsonPropertyName("providerDefined")]
  ProviderDefined = 2,
}
