//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Recommend;

/// <summary>
/// SearchRecommendRulesResponse
/// </summary>
[DataContract(Name = "searchRecommendRulesResponse")]
[JsonObject(MemberSerialization.OptOut)]
public partial class SearchRecommendRulesResponse
{
  /// <summary>
  /// Initializes a new instance of the SearchRecommendRulesResponse class.
  /// </summary>
  [JsonConstructor]
  public SearchRecommendRulesResponse() { }
  /// <summary>
  /// Initializes a new instance of the SearchRecommendRulesResponse class.
  /// </summary>
  /// <param name="hits">Fetched rules. (required).</param>
  /// <param name="nbHits">Number of hits the search query matched. (required).</param>
  /// <param name="page">Page to retrieve (the first page is &#x60;0&#x60;, not &#x60;1&#x60;). (required) (default to 0).</param>
  /// <param name="nbPages">Number of pages of results for the current query. (required).</param>
  public SearchRecommendRulesResponse(List<RuleResponse> hits, int? nbHits, int? page, int? nbPages)
  {
    Hits = hits ?? throw new ArgumentNullException(nameof(hits));
    NbHits = nbHits;
    Page = page;
    NbPages = nbPages;
  }

  /// <summary>
  /// Fetched rules.
  /// </summary>
  /// <value>Fetched rules.</value>
  [DataMember(Name = "hits", IsRequired = true, EmitDefaultValue = false)]
  public List<RuleResponse> Hits { get; set; }

  /// <summary>
  /// Number of hits the search query matched.
  /// </summary>
  /// <value>Number of hits the search query matched.</value>
  [DataMember(Name = "nbHits", IsRequired = true, EmitDefaultValue = false)]
  public int? NbHits { get; set; }

  /// <summary>
  /// Page to retrieve (the first page is `0`, not `1`).
  /// </summary>
  /// <value>Page to retrieve (the first page is `0`, not `1`).</value>
  [DataMember(Name = "page", IsRequired = true, EmitDefaultValue = false)]
  public int? Page { get; set; }

  /// <summary>
  /// Number of pages of results for the current query.
  /// </summary>
  /// <value>Number of pages of results for the current query.</value>
  [DataMember(Name = "nbPages", IsRequired = true, EmitDefaultValue = false)]
  public int? NbPages { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class SearchRecommendRulesResponse {\n");
    sb.Append("  Hits: ").Append(Hits).Append("\n");
    sb.Append("  NbHits: ").Append(NbHits).Append("\n");
    sb.Append("  Page: ").Append(Page).Append("\n");
    sb.Append("  NbPages: ").Append(NbPages).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonConvert.SerializeObject(this, Formatting.Indented);
  }

}

