//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AgentStudio;

/// <summary>
/// Support Compatibility modes for the completion API.
/// </summary>
/// <value>Support Compatibility modes for the completion API.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<CompatibilityMode>))]
public enum CompatibilityMode
{
  /// <summary>
  /// Enum AiSdk4 for value: ai-sdk-4
  /// </summary>
  [JsonPropertyName("ai-sdk-4")]
  AiSdk4 = 1,

  /// <summary>
  /// Enum AiSdk5 for value: ai-sdk-5
  /// </summary>
  [JsonPropertyName("ai-sdk-5")]
  AiSdk5 = 2,
}
