//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AgentStudio;

/// <summary>
/// MessagePart
/// </summary>
[JsonConverter(typeof(MessagePartJsonConverter))]
public partial class MessagePart : AbstractSchema
{
  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a ToolResultPart
  /// </summary>
  /// <param name="actualInstance">An instance of ToolResultPart.</param>
  public MessagePart(ToolResultPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a TextPart
  /// </summary>
  /// <param name="actualInstance">An instance of TextPart.</param>
  public MessagePart(TextPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a ToolCallPart
  /// </summary>
  /// <param name="actualInstance">An instance of ToolCallPart.</param>
  public MessagePart(ToolCallPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a StartPart
  /// </summary>
  /// <param name="actualInstance">An instance of StartPart.</param>
  public MessagePart(StartPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a StartStepPart
  /// </summary>
  /// <param name="actualInstance">An instance of StartStepPart.</param>
  public MessagePart(StartStepPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a ReasoningPart
  /// </summary>
  /// <param name="actualInstance">An instance of ReasoningPart.</param>
  public MessagePart(ReasoningPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Initializes a new instance of the MessagePart class
  /// with a ToolApprovalRequestPart
  /// </summary>
  /// <param name="actualInstance">An instance of ToolApprovalRequestPart.</param>
  public MessagePart(ToolApprovalRequestPart actualInstance)
  {
    ActualInstance =
      actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
  }

  /// <summary>
  /// Gets or Sets ActualInstance
  /// </summary>
  public sealed override object ActualInstance { get; set; }

  /// <summary>
  /// Get the actual instance of `ToolResultPart`. If the actual instance is not `ToolResultPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of ToolResultPart</returns>
  public ToolResultPart AsToolResultPart()
  {
    return (ToolResultPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `TextPart`. If the actual instance is not `TextPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of TextPart</returns>
  public TextPart AsTextPart()
  {
    return (TextPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `ToolCallPart`. If the actual instance is not `ToolCallPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of ToolCallPart</returns>
  public ToolCallPart AsToolCallPart()
  {
    return (ToolCallPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `StartPart`. If the actual instance is not `StartPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of StartPart</returns>
  public StartPart AsStartPart()
  {
    return (StartPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `StartStepPart`. If the actual instance is not `StartStepPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of StartStepPart</returns>
  public StartStepPart AsStartStepPart()
  {
    return (StartStepPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `ReasoningPart`. If the actual instance is not `ReasoningPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of ReasoningPart</returns>
  public ReasoningPart AsReasoningPart()
  {
    return (ReasoningPart)ActualInstance;
  }

  /// <summary>
  /// Get the actual instance of `ToolApprovalRequestPart`. If the actual instance is not `ToolApprovalRequestPart`,
  /// the InvalidClassException will be thrown
  /// </summary>
  /// <returns>An instance of ToolApprovalRequestPart</returns>
  public ToolApprovalRequestPart AsToolApprovalRequestPart()
  {
    return (ToolApprovalRequestPart)ActualInstance;
  }

  /// <summary>
  /// Check if the actual instance is of `ToolResultPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsToolResultPart()
  {
    return ActualInstance.GetType() == typeof(ToolResultPart);
  }

  /// <summary>
  /// Check if the actual instance is of `TextPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsTextPart()
  {
    return ActualInstance.GetType() == typeof(TextPart);
  }

  /// <summary>
  /// Check if the actual instance is of `ToolCallPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsToolCallPart()
  {
    return ActualInstance.GetType() == typeof(ToolCallPart);
  }

  /// <summary>
  /// Check if the actual instance is of `StartPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsStartPart()
  {
    return ActualInstance.GetType() == typeof(StartPart);
  }

  /// <summary>
  /// Check if the actual instance is of `StartStepPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsStartStepPart()
  {
    return ActualInstance.GetType() == typeof(StartStepPart);
  }

  /// <summary>
  /// Check if the actual instance is of `ReasoningPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsReasoningPart()
  {
    return ActualInstance.GetType() == typeof(ReasoningPart);
  }

  /// <summary>
  /// Check if the actual instance is of `ToolApprovalRequestPart` type.
  /// </summary>
  /// <returns>Whether or not the instance is the type</returns>
  public bool IsToolApprovalRequestPart()
  {
    return ActualInstance.GetType() == typeof(ToolApprovalRequestPart);
  }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    var sb = new StringBuilder();
    sb.Append("class MessagePart {\n");
    sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public override string ToJson()
  {
    return JsonSerializer.Serialize(ActualInstance, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not MessagePart input)
    {
      return false;
    }

    return ActualInstance.Equals(input.ActualInstance);
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (ActualInstance != null)
        hashCode = hashCode * 59 + ActualInstance.GetHashCode();
      return hashCode;
    }
  }
}

/// <summary>
/// Custom JSON converter for MessagePart
/// </summary>
public class MessagePartJsonConverter : JsonConverter<MessagePart>
{
  /// <summary>
  /// Check if the object can be converted
  /// </summary>
  /// <param name="objectType">Object type</param>
  /// <returns>True if the object can be converted</returns>
  public override bool CanConvert(Type objectType)
  {
    return objectType == typeof(MessagePart);
  }

  /// <summary>
  /// To convert a JSON string into an object
  /// </summary>
  /// <param name="reader">JSON reader</param>
  /// <param name="typeToConvert">Object type</param>
  /// <param name="options">Serializer options</param>
  /// <returns>The object converted from the JSON string</returns>
  public override MessagePart Read(
    ref Utf8JsonReader reader,
    Type typeToConvert,
    JsonSerializerOptions options
  )
  {
    var jsonDocument = JsonDocument.ParseValue(ref reader);
    var root = jsonDocument.RootElement;
    if (root.TryGetProperty("type", out JsonElement discriminatorElement))
    {
      string discriminatorValue = discriminatorElement.GetString();
      if (discriminatorValue == "reasoning")
      {
        return new MessagePart(jsonDocument.Deserialize<ReasoningPart>(JsonConfig.Options));
      }
      if (discriminatorValue == "start")
      {
        return new MessagePart(jsonDocument.Deserialize<StartPart>(JsonConfig.Options));
      }
      if (discriminatorValue == "start-step")
      {
        return new MessagePart(jsonDocument.Deserialize<StartStepPart>(JsonConfig.Options));
      }
      if (discriminatorValue == "text")
      {
        return new MessagePart(jsonDocument.Deserialize<TextPart>(JsonConfig.Options));
      }
      if (discriminatorValue == "tool-approval-request")
      {
        return new MessagePart(
          jsonDocument.Deserialize<ToolApprovalRequestPart>(JsonConfig.Options)
        );
      }
      if (discriminatorValue == "tool-call")
      {
        return new MessagePart(jsonDocument.Deserialize<ToolCallPart>(JsonConfig.Options));
      }
      if (discriminatorValue == "tool-result")
      {
        return new MessagePart(jsonDocument.Deserialize<ToolResultPart>(JsonConfig.Options));
      }
    }
    if (root.ValueKind == JsonValueKind.Object && root.TryGetProperty("output", out _))
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<ToolResultPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(
          $"Failed to deserialize into ToolResultPart: {exception}"
        );
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<TextPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine($"Failed to deserialize into TextPart: {exception}");
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<ToolCallPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine($"Failed to deserialize into ToolCallPart: {exception}");
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<StartPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine($"Failed to deserialize into StartPart: {exception}");
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<StartStepPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(
          $"Failed to deserialize into StartStepPart: {exception}"
        );
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(jsonDocument.Deserialize<ReasoningPart>(JsonConfig.Options));
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(
          $"Failed to deserialize into ReasoningPart: {exception}"
        );
      }
    }
    if (root.ValueKind == JsonValueKind.Object)
    {
      try
      {
        return new MessagePart(
          jsonDocument.Deserialize<ToolApprovalRequestPart>(JsonConfig.Options)
        );
      }
      catch (Exception exception)
      {
        // deserialization failed, try the next one
        System.Diagnostics.Debug.WriteLine(
          $"Failed to deserialize into ToolApprovalRequestPart: {exception}"
        );
      }
    }
    throw new InvalidDataException(
      $"The JSON string cannot be deserialized into any schema defined."
    );
  }

  /// <summary>
  /// To write the JSON string
  /// </summary>
  /// <param name="writer">JSON writer</param>
  /// <param name="value">MessagePart to be converted into a JSON string</param>
  /// <param name="options">JSON Serializer options</param>
  public override void Write(
    Utf8JsonWriter writer,
    MessagePart value,
    JsonSerializerOptions options
  )
  {
    writer.WriteRawValue(value.ToJson());
  }
}
