//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AgentStudio;

/// <summary>
/// ReasoningPartV4
/// </summary>
public partial class ReasoningPartV4
{
  /// <summary>
  /// Initializes a new instance of the ReasoningPartV4 class.
  /// </summary>
  [JsonConstructor]
  public ReasoningPartV4() { }

  /// <summary>
  /// Initializes a new instance of the ReasoningPartV4 class.
  /// </summary>
  /// <param name="reasoning">reasoning (required).</param>
  public ReasoningPartV4(string reasoning)
  {
    Reasoning = reasoning ?? throw new ArgumentNullException(nameof(reasoning));
  }

  /// <summary>
  /// Gets or Sets Type
  /// </summary>
  [JsonPropertyName("type")]
  public string Type { get; set; }

  /// <summary>
  /// Gets or Sets Reasoning
  /// </summary>
  [JsonPropertyName("reasoning")]
  public string Reasoning { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class ReasoningPartV4 {\n");
    sb.Append("  Type: ").Append(Type).Append("\n");
    sb.Append("  Reasoning: ").Append(Reasoning).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not ReasoningPartV4 input)
    {
      return false;
    }

    return (Type == input.Type || (Type != null && Type.Equals(input.Type)))
      && (Reasoning == input.Reasoning || (Reasoning != null && Reasoning.Equals(input.Reasoning)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (Type != null)
      {
        hashCode = (hashCode * 59) + Type.GetHashCode();
      }
      if (Reasoning != null)
      {
        hashCode = (hashCode * 59) + Reasoning.GetHashCode();
      }
      return hashCode;
    }
  }
}
