//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AgentStudio;

/// <summary>
/// A string array search parameter with exposure control, constraints, and merge behavior.
/// </summary>
public partial class StringArrayParam
{
  /// <summary>
  /// Initializes a new instance of the StringArrayParam class.
  /// </summary>
  [JsonConstructor]
  public StringArrayParam() { }

  /// <summary>
  /// Initializes a new instance of the StringArrayParam class.
  /// </summary>
  /// <param name="exposed">exposed (required).</param>
  public StringArrayParam(bool exposed)
  {
    Exposed = exposed;
  }

  /// <summary>
  /// Gets or Sets Exposed
  /// </summary>
  [JsonPropertyName("exposed")]
  public bool Exposed { get; set; }

  /// <summary>
  /// Gets or Sets Default
  /// </summary>
  [JsonPropertyName("default")]
  public List<string> Default { get; set; }

  /// <summary>
  /// Gets or Sets Constraint
  /// </summary>
  [JsonPropertyName("constraint")]
  public StringArrayParamConstraint Constraint { get; set; }

  /// <summary>
  /// Gets or Sets Merge
  /// </summary>
  [JsonPropertyName("merge")]
  public bool? Merge { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class StringArrayParam {\n");
    sb.Append("  Exposed: ").Append(Exposed).Append("\n");
    sb.Append("  Default: ").Append(Default).Append("\n");
    sb.Append("  Constraint: ").Append(Constraint).Append("\n");
    sb.Append("  Merge: ").Append(Merge).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not StringArrayParam input)
    {
      return false;
    }

    return (Exposed == input.Exposed || Exposed.Equals(input.Exposed))
      && (
        Default == input.Default
        || Default != null && input.Default != null && Default.SequenceEqual(input.Default)
      )
      && (
        Constraint == input.Constraint
        || (Constraint != null && Constraint.Equals(input.Constraint))
      )
      && (Merge == input.Merge || (Merge != null && Merge.Equals(input.Merge)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      hashCode = (hashCode * 59) + Exposed.GetHashCode();
      if (Default != null)
      {
        hashCode = (hashCode * 59) + Default.GetHashCode();
      }
      if (Constraint != null)
      {
        hashCode = (hashCode * 59) + Constraint.GetHashCode();
      }
      if (Merge != null)
      {
        hashCode = (hashCode * 59) + Merge.GetHashCode();
      }
      return hashCode;
    }
  }
}
