//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AgentStudio;

/// <summary>
/// Model for tool invocation in a Message.
/// </summary>
public partial class ToolPartV5
{
  /// <summary>
  /// Gets or Sets State
  /// </summary>
  [JsonPropertyName("state")]
  public ToolState? State { get; set; }

  /// <summary>
  /// Initializes a new instance of the ToolPartV5 class.
  /// </summary>
  [JsonConstructor]
  public ToolPartV5() { }

  /// <summary>
  /// Initializes a new instance of the ToolPartV5 class.
  /// </summary>
  /// <param name="type">type (required).</param>
  /// <param name="toolCallId">toolCallId (required).</param>
  public ToolPartV5(string type, string toolCallId)
  {
    Type = type ?? throw new ArgumentNullException(nameof(type));
    ToolCallId = toolCallId ?? throw new ArgumentNullException(nameof(toolCallId));
  }

  /// <summary>
  /// Gets or Sets Type
  /// </summary>
  [JsonPropertyName("type")]
  public string Type { get; set; }

  /// <summary>
  /// Gets or Sets ToolCallId
  /// </summary>
  [JsonPropertyName("toolCallId")]
  public string ToolCallId { get; set; }

  /// <summary>
  /// Gets or Sets Input
  /// </summary>
  [JsonPropertyName("input")]
  public Dictionary<string, object> Input { get; set; }

  /// <summary>
  /// Gets or Sets Output
  /// </summary>
  [JsonPropertyName("output")]
  public Dictionary<string, object> Output { get; set; }

  /// <summary>
  /// Gets or Sets ErrorText
  /// </summary>
  [JsonPropertyName("errorText")]
  public string ErrorText { get; set; }

  /// <summary>
  /// Gets or Sets ProviderOptions
  /// </summary>
  [JsonPropertyName("providerOptions")]
  public Dictionary<string, object> ProviderOptions { get; set; }

  /// <summary>
  /// Gets or Sets RequiresApproval
  /// </summary>
  [JsonPropertyName("requiresApproval")]
  public bool? RequiresApproval { get; set; }

  /// <summary>
  /// Gets or Sets Description
  /// </summary>
  [JsonPropertyName("description")]
  public string Description { get; set; }

  /// <summary>
  /// Gets or Sets ArgsHash
  /// </summary>
  [JsonPropertyName("argsHash")]
  public string ArgsHash { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class ToolPartV5 {\n");
    sb.Append("  Type: ").Append(Type).Append("\n");
    sb.Append("  ToolCallId: ").Append(ToolCallId).Append("\n");
    sb.Append("  State: ").Append(State).Append("\n");
    sb.Append("  Input: ").Append(Input).Append("\n");
    sb.Append("  Output: ").Append(Output).Append("\n");
    sb.Append("  ErrorText: ").Append(ErrorText).Append("\n");
    sb.Append("  ProviderOptions: ").Append(ProviderOptions).Append("\n");
    sb.Append("  RequiresApproval: ").Append(RequiresApproval).Append("\n");
    sb.Append("  Description: ").Append(Description).Append("\n");
    sb.Append("  ArgsHash: ").Append(ArgsHash).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not ToolPartV5 input)
    {
      return false;
    }

    return (Type == input.Type || (Type != null && Type.Equals(input.Type)))
      && (
        ToolCallId == input.ToolCallId
        || (ToolCallId != null && ToolCallId.Equals(input.ToolCallId))
      )
      && (State == input.State || State.Equals(input.State))
      && (
        Input == input.Input
        || Input != null && input.Input != null && Input.SequenceEqual(input.Input)
      )
      && (
        Output == input.Output
        || Output != null && input.Output != null && Output.SequenceEqual(input.Output)
      )
      && (ErrorText == input.ErrorText || (ErrorText != null && ErrorText.Equals(input.ErrorText)))
      && (
        ProviderOptions == input.ProviderOptions
        || ProviderOptions != null
          && input.ProviderOptions != null
          && ProviderOptions.SequenceEqual(input.ProviderOptions)
      )
      && (
        RequiresApproval == input.RequiresApproval
        || RequiresApproval.Equals(input.RequiresApproval)
      )
      && (
        Description == input.Description
        || (Description != null && Description.Equals(input.Description))
      )
      && (ArgsHash == input.ArgsHash || (ArgsHash != null && ArgsHash.Equals(input.ArgsHash)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (Type != null)
      {
        hashCode = (hashCode * 59) + Type.GetHashCode();
      }
      if (ToolCallId != null)
      {
        hashCode = (hashCode * 59) + ToolCallId.GetHashCode();
      }
      hashCode = (hashCode * 59) + State.GetHashCode();
      if (Input != null)
      {
        hashCode = (hashCode * 59) + Input.GetHashCode();
      }
      if (Output != null)
      {
        hashCode = (hashCode * 59) + Output.GetHashCode();
      }
      if (ErrorText != null)
      {
        hashCode = (hashCode * 59) + ErrorText.GetHashCode();
      }
      if (ProviderOptions != null)
      {
        hashCode = (hashCode * 59) + ProviderOptions.GetHashCode();
      }
      hashCode = (hashCode * 59) + RequiresApproval.GetHashCode();
      if (Description != null)
      {
        hashCode = (hashCode * 59) + Description.GetHashCode();
      }
      if (ArgsHash != null)
      {
        hashCode = (hashCode * 59) + ArgsHash.GetHashCode();
      }
      return hashCode;
    }
  }
}
