//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Text;
using System.Linq;
using System.Text.Json.Serialization;
using System.Collections.Generic;
using Algolia.Search.Serializer;
using System.Text.Json;

namespace Algolia.Search.Models.Search;

/// <summary>
/// Determines how the [Exact ranking criterion](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/override-search-engine-defaults/in-depth/adjust-exact-settings/#turn-off-exact-for-some-attributes) is computed when the query contains only one word.
/// </summary>
/// <value>Determines how the [Exact ranking criterion](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/override-search-engine-defaults/in-depth/adjust-exact-settings/#turn-off-exact-for-some-attributes) is computed when the query contains only one word.</value>
public enum ExactOnSingleWordQuery
{
  /// <summary>
  /// Enum Attribute for value: attribute
  /// </summary>
  [JsonPropertyName("attribute")]
  Attribute = 1,

  /// <summary>
  /// Enum None for value: none
  /// </summary>
  [JsonPropertyName("none")]
  None = 2,

  /// <summary>
  /// Enum Word for value: word
  /// </summary>
  [JsonPropertyName("word")]
  Word = 3
}

