//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Search;

/// <summary>
/// A/B test target criteria. Only present for v2 and later tests.
/// </summary>
public partial class FetchedIndexAbTestTarget
{
  /// <summary>
  /// Initializes a new instance of the FetchedIndexAbTestTarget class.
  /// </summary>
  [JsonConstructor]
  public FetchedIndexAbTestTarget() { }

  /// <summary>
  /// Initializes a new instance of the FetchedIndexAbTestTarget class.
  /// </summary>
  /// <param name="indexName">Index name to match. Use `*` to target the entire application. (required).</param>
  public FetchedIndexAbTestTarget(string indexName)
  {
    IndexName = indexName ?? throw new ArgumentNullException(nameof(indexName));
  }

  /// <summary>
  /// Index name to match. Use `*` to target the entire application.
  /// </summary>
  /// <value>Index name to match. Use `*` to target the entire application.</value>
  [JsonPropertyName("indexName")]
  public string IndexName { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class FetchedIndexAbTestTarget {\n");
    sb.Append("  IndexName: ").Append(IndexName).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not FetchedIndexAbTestTarget input)
    {
      return false;
    }

    return (
      IndexName == input.IndexName || (IndexName != null && IndexName.Equals(input.IndexName))
    );
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (IndexName != null)
      {
        hashCode = (hashCode * 59) + IndexName.GetHashCode();
      }
      return hashCode;
    }
  }
}
