//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;
using Algolia.Search.Models.Common;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Search;

/// <summary>
/// Defines logType
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum LogType
{
  /// <summary>
  /// Enum All for value: all
  /// </summary>
  [EnumMember(Value = "all")]
  All = 1,

  /// <summary>
  /// Enum Query for value: query
  /// </summary>
  [EnumMember(Value = "query")]
  Query = 2,

  /// <summary>
  /// Enum Build for value: build
  /// </summary>
  [EnumMember(Value = "build")]
  Build = 3,

  /// <summary>
  /// Enum Error for value: error
  /// </summary>
  [EnumMember(Value = "error")]
  Error = 4
}

