//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.Search;

/// <summary>
/// AI-generated metadata returned alongside search results. Present when Algolia AI features such as [Query Categorization](https://www.algolia.com/doc/guides/algolia-ai/query-categorization/) are enabled.
/// </summary>
public partial class ResponseExtensions
{
  /// <summary>
  /// Initializes a new instance of the ResponseExtensions class.
  /// </summary>
  public ResponseExtensions() { }

  /// <summary>
  /// Gets or Sets QueryCategorization
  /// </summary>
  [JsonPropertyName("queryCategorization")]
  public QueryCategorization QueryCategorization { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class ResponseExtensions {\n");
    sb.Append("  QueryCategorization: ").Append(QueryCategorization).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not ResponseExtensions input)
    {
      return false;
    }

    return (
      QueryCategorization == input.QueryCategorization
      || (QueryCategorization != null && QueryCategorization.Equals(input.QueryCategorization))
    );
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (QueryCategorization != null)
      {
        hashCode = (hashCode * 59) + QueryCategorization.GetHashCode();
      }
      return hashCode;
    }
  }
}
