//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Algolia.Search.Models;

namespace Algolia.Search.Analytics.Models
{
  /// <summary>
  /// UserWithDate
  /// </summary>
  [DataContract(Name = "userWithDate")]
  public partial class UserWithDate : IEquatable<UserWithDate>
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="UserWithDate" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected UserWithDate() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="UserWithDate" /> class.
    /// </summary>
    /// <param name="date">Date of the event in the format YYYY-MM-DD. (required).</param>
    /// <param name="count">Number of occurrences. (required).</param>
    public UserWithDate(string date = default(string), int count = default(int))
    {
      // to ensure "date" is required (not null)
      if (date == null)
      {
        throw new ArgumentNullException("date is a required property for UserWithDate and cannot be null");
      }
      this.Date = date;
      this.Count = count;
    }

    /// <summary>
    /// Date of the event in the format YYYY-MM-DD.
    /// </summary>
    /// <value>Date of the event in the format YYYY-MM-DD.</value>
    [DataMember(Name = "date", IsRequired = true, EmitDefaultValue = true)]
    public string Date { get; set; }

    /// <summary>
    /// Number of occurrences.
    /// </summary>
    /// <value>Number of occurrences.</value>
    [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
    public int Count { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      StringBuilder sb = new StringBuilder();
      sb.Append("class UserWithDate {\n");
      sb.Append("  Date: ").Append(Date).Append("\n");
      sb.Append("  Count: ").Append(Count).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
      return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
      return this.Equals(input as UserWithDate);
    }

    /// <summary>
    /// Returns true if UserWithDate instances are equal
    /// </summary>
    /// <param name="input">Instance of UserWithDate to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(UserWithDate input)
    {
      if (input == null)
      {
        return false;
      }
      return
          (
              this.Date == input.Date ||
              (this.Date != null &&
              this.Date.Equals(input.Date))
          ) &&
          (
              this.Count == input.Count ||
              this.Count.Equals(input.Count)
          );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      unchecked // Overflow is fine, just wrap
      {
        int hashCode = 41;
        if (this.Date != null)
        {
          hashCode = (hashCode * 59) + this.Date.GetHashCode();
        }
        hashCode = (hashCode * 59) + this.Count.GetHashCode();
        return hashCode;
      }
    }

  }

}
