name: Release packages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish
    runs-on: ubuntu-22.04
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.100

      - name: Create Nugget package
        run: dotnet pack --configuration Release --output nugget

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet package
        run: dotnet nuget push "nugget/*.nupkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
